calculator functionality
sjdev2212/math-magicians pull request #3
Opened 2021-12-01 20:21 UTC by sj1978

In this feature I : 
Copied files given by microverse and place them inside a logic folder.
Added functionality to the calculator using those files.
Checked linters.

2021-12-01 21:12 UTC, omar-labana requested changes
Hi @sj1978, 

Excellent work so far! 👌
The repo is quite professional, and the UI is looking amazing. ✔️👌
You have implemented almost all the required features. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
_N/A_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-01 21:12 UTC, omar-labana commented on src/components/Calculator.js
> +        total: '541',
- [x] Please clear this static value from the internal state. The output of the calculator when first launched is `541`.

2021-12-01 21:12 UTC, omar-labana commented on src/components/Calculator.js
> +            <button type="button" className="btn equal operation" onClick={() => this.pressedButton(obj, '=')}>=</button>
- [ ] I would suggest practicing passing Props to child components of the Calculate.js component, you should create a button component then pass down the button operation along with the stickhandler to it.

2021-12-02 07:09 UTC, ArthurGC approved these changes
# Approved project!  💯 ✅ 🥳 🎈 🎉
Hi  @sj1978 

Amazing job implementing suggestions from the previous reviewer! 💯 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media1.giphy.com/media/3o7buh8WbaZLupolXi/giphy.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2021-12-02 13:46 UTC, merged